
import { HeroComponent } from '../../components/hero-component/hero-component';
import { VideoCard } from '../../components/video-card/video-card';
import { Component } from '@angular/core';
import { NgFor } from '@angular/common';


export interface VideoCardType {
  id: number;
  title: string;
  thumbnail: string;
  thumbnailLarge?: string;
  description?: string;   // optional
  type: 'Movie' | 'Series' | 'Sports';  // restrict to only these types
  genre?: string[];       // optional array
  year?: number;
  duration?: string;
  rating?: string;
  seasons?: number
}




@Component({
  selector: 'app-home',
  imports: [HeroComponent, VideoCard, NgFor],
  templateUrl: './home.html',
  styleUrl: './home.css'
})
export class Home {


  videoCards: VideoCardType[] = [
    {
      id: 1,
      title: "Avengers: Endgame",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1385/1753093531385-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2122/1747917722122-v",
      description: "Superheroes unite to battle the most powerful villain in the universe.",
      type: "Movie",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2019,
      duration: "3h 1m",
      rating: "9.0",
    },
    {
      id: 2,
      title: "House of the Dragon",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3235/1754460993235-i",
      description: "The reign of House Targaryen begins. A prequel to Game of Thrones.",
      type: "Series",
      genre: ["Drama", "Fantasy"],
      year: 2022,
      seasons: 2,
      rating: "8.7",
    },
    {
      id: 3,
      title: "The Mandalorian",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7250/1754473677250-v",
      description: "A lone bounty hunter travels through the galaxy protecting Grogu (Baby Yoda).",
      type: "Series",
      genre: ["Sci-Fi", "Action"],
      year: 2019,
      seasons: 3,
      rating: "8.8",
    },
    {
      id: 4,
      title: "Black Panther: Wakanda Forever",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/805/1755108030805-v",
      description: "The people of Wakanda fight to protect their home after King T’Challa’s death.",
      type: "Movie",
      genre: ["Action", "Drama"],
      year: 2022,
      duration: "2h 41m",
      rating: "7.5",
    },
    {
      id: 5,
      title: "Cricket World Cup Highlights",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1334/1753724211334-v",
      description: "Highlights and replays of ICC World Cup 2023 matches.",
      type: "Sports",
      genre: ["Cricket"],
      year: 2023,
      duration: "Highlights",
      rating: "N/A",
    },
    {
      id: 1,
      title: "Avengers: Endgame",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2122/1747917722122-v",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1385/1753093531385-i",
      description: "Superheroes unite to battle the most powerful villain in the universe.",
      type: "Movie",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2019,
      duration: "3h 1m",
      rating: "9.0",
    },
    {
      id: 2,
      title: "House of the Dragon",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3235/1754460993235-i",
      description: "The reign of House Targaryen begins. A prequel to Game of Thrones.",
      type: "Series",
      genre: ["Drama", "Fantasy"],
      year: 2022,
      seasons: 2,
      rating: "8.7",
    },
    {
      id: 3,
      title: "The Mandalorian",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7250/1754473677250-v",
      description: "A lone bounty hunter travels through the galaxy protecting Grogu (Baby Yoda).",
      type: "Series",
      genre: ["Sci-Fi", "Action"],
      year: 2019,
      seasons: 3,
      rating: "8.8",
    },
    {
      id: 4,
      title: "Black Panther: Wakanda Forever",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/805/1755108030805-v",
      description: "The people of Wakanda fight to protect their home after King T’Challa’s death.",
      type: "Movie",
      genre: ["Action", "Drama"],
      year: 2022,
      duration: "2h 41m",
      rating: "7.5",
    },
    {
      id: 5,
      title: "Cricket World Cup Highlights",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1334/1753724211334-v",
      description: "Highlights and replays of ICC World Cup 2023 matches.",
      type: "Sports",
      genre: ["Cricket"],
      year: 2023,
      duration: "Highlights",
      rating: "N/A",
    }
  ];
  latestEpisode = [
    {
      id: 1,
      title: "Inception",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2483/1755626082483-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90/sources/r1/cms/prod/2714/1755626012714-v",
      description: "A thief enters people’s dreams to steal secrets, but faces the ultimate heist of planting an idea.",
      type: "Movie",
      genre: ["Sci-Fi", "Thriller", "Action"],
      year: 2010,
      duration: "2h 28m",
      rating: "8.8",
    },
    {
      id: 2,
      title: "The Dark Knight",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4840/1747736464840-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/8274/1747736338274-v",
      description: "Batman faces his greatest test against the Joker, who seeks to plunge Gotham into chaos.",
      type: "Movie",
      genre: ["Action", "Crime", "Drama"],
      year: 2008,
      duration: "2h 32m",
      rating: "9.0",
    },
    {
      id: 3,
      title: "Interstellar",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/8035/1748996718035-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1434/1748996681434-v",
      description: "A team of explorers travels through a wormhole in space to save humanity from extinction.",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure", "Drama"],
      year: 2014,
      duration: "2h 49m",
      rating: "8.6",
    },
    {
      id: 4,
      title: "Stranger Things",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3471/1749174053471-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3471/1749174053471-i",
      description: "Kids uncover dark secrets when a friend disappears and a strange girl with powers appears.",
      type: "Series",
      genre: ["Mystery", "Thriller", "Sci-Fi"],
      year: 2016,
      duration: "4 Seasons",
      rating: "8.7",
    },
    {
      id: 5,
      title: "Breaking Bad",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/8384/1738315988384-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/471/1738316010471-v",
      description: "A chemistry teacher turned meth kingpin struggles to secure his family’s future.",
      type: "Series",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2008,
      duration: "5 Seasons",
      rating: "9.5",
    },
    {
      id: 6,
      title: "The Matrix",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_1920/sources/r1/cms/prod/2489/1754473712489-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7250/1754473677250-v",
      description: "A hacker discovers that reality is a simulation and joins a rebellion against machines.",
      type: "Movie",
      genre: ["Sci-Fi", "Action"],
      year: 1999,
      duration: "2h 16m",
      rating: "8.7",
    },
    {
      id: 7,
      title: "Game of Thrones",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9580/1749169569580-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6972/1749169526972-v",
      description: "Noble families vie for the Iron Throne as an ancient threat rises in the north.",
      type: "Series",
      genre: ["Fantasy", "Drama", "Adventure"],
      year: 2011,
      duration: "8 Seasons",
      rating: "9.2",
    },
    {
      id: 8,
      title: "The Lion King",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3132/1383132-i-011cefc50da9",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7527/267527-v",
      description: "A lion cub flees after tragedy strikes, only to return and reclaim his kingdom.",
      type: "Movie",
      genre: ["Animation", "Drama", "Adventure"],
      year: 1994,
      duration: "1h 28m",
      rating: "8.5",
    },
    {
      id: 9,
      title: "Black Panther",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7522/1734435617522-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4310/1734435614310-v",
      description: "T’Challa becomes king of Wakanda and must defend his nation from hidden enemies.",
      type: "Movie",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2018,
      duration: "2h 14m",
      rating: "7.3",
    },
    {
      id: 10,
      title: "The Mandalorian",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9032/1751047759032-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9084/1751047729084-v",
      description: "A lone bounty hunter travels the galaxy, protecting a mysterious child.",
      type: "Series",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2019,
      duration: "3 Seasons",
      rating: "8.7",
    },
    {
      id: 11,
      title: "Avatar",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3232/1423232-i-050f622bde39",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3229/1423229-v-38316a3e497f",
      description: "A marine on an alien world struggles between duty and a newfound connection with nature.",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure", "Fantasy"],
      year: 2009,
      duration: "2h 42m",
      rating: "7.9",
    },
    {
      id: 12,
      title: "Joker",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5857/1745986875857-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/8429/1745986818429-v",
      description: "A failed comedian spirals into madness and becomes Gotham’s notorious villain.",
      type: "Movie",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2019,
      duration: "2h 2m",
      rating: "8.4",
    },
    {
      id: 13,
      title: "Money Heist",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7149/1751706547149-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6876/1751706436876-v",
      description: "A mastermind gathers criminals to carry out the biggest heist in Spain’s history.",
      type: "Series",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2017,
      duration: "5 Seasons",
      rating: "8.2",
    },
    {
      id: 14,
      title: "Spider-Man: No Way Home",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7626/1755603447626-i",
      thumbnail: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/4109/1755603424109-t",
      description: "Peter Parker seeks help from Doctor Strange, unleashing chaos across the multiverse.",
      type: "Movie",
      genre: ["Action", "Adventure", "Fantasy"],
      year: 2021,
      duration: "2h 28m",
      rating: "8.3",
    },
  ];

  sparksCard = [
    {
      id: 1,
      title: "Inception",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2587/1740577422587-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/359/1740577350359-v",
      description: "A thief enters people’s dreams to steal secrets, but faces the ultimate heist of planting an idea.",
      type: "Movie",
      genre: ["Sci-Fi", "Thriller", "Action"],
      year: 2010,
      duration: "2h 28m",
      rating: "8.8",
    },
    {
      id: 2,
      title: "The Dark Knight",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1464/1753121881464-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4186/1754287614186-v",
      description: "Batman faces his greatest test against the Joker, who seeks to plunge Gotham into chaos.",
      type: "Movie",
      genre: ["Action", "Crime", "Drama"],
      year: 2008,
      duration: "2h 32m",
      rating: "9.0",
    },
    {
      id: 3,
      title: "Interstellar",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9416/1739394169416-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2122/1747917722122-v",
      description: "A team of explorers travels through a wormhole in space to save humanity from extinction.",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure", "Drama"],
      year: 2014,
      duration: "2h 49m",
      rating: "8.6",
    },
    {
      id: 4,
      title: "Stranger Things",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3259/1743498863259-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3259/1743498863259-i",
      description: "Kids uncover dark secrets when a friend disappears and a strange girl with powers appears.",
      type: "Series",
      genre: ["Mystery", "Thriller", "Sci-Fi"],
      year: 2016,
      duration: "4 Seasons",
      rating: "8.7",
    },
    {
      id: 5,
      title: "Breaking Bad",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7517/1744791887517-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3240/1744787323240-v",
      description: "A chemistry teacher turned meth kingpin struggles to secure his family’s future.",
      type: "Series",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2008,
      duration: "5 Seasons",
      rating: "9.5",
    },
    {
      id: 6,
      title: "The Matrix",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2869/1743502772869-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2448/1743496862448-v",
      description: "A hacker discovers that reality is a simulation and joins a rebellion against machines.",
      type: "Movie",
      genre: ["Sci-Fi", "Action"],
      year: 1999,
      duration: "2h 16m",
      rating: "8.7",
    },
    {
      id: 7,
      title: "Game of Thrones",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3235/1754460993235-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5166/1754460935166-v",
      description: "Noble families vie for the Iron Throne as an ancient threat rises in the north.",
      type: "Series",
      genre: ["Fantasy", "Drama", "Adventure"],
      year: 2011,
      duration: "8 Seasons",
      rating: "9.2",
    },
    {
      id: 8,
      title: "The Lion King",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6775/1747925436775-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4884/1747925414884-v",
      description: "A lion cub flees after tragedy strikes, only to return and reclaim his kingdom.",
      type: "Movie",
      genre: ["Animation", "Drama", "Adventure"],
      year: 1994,
      duration: "1h 28m",
      rating: "8.5",
    },
    {
      id: 9,
      title: "Black Panther",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7522/1734435617522-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4310/1734435614310-v",
      description: "T’Challa becomes king of Wakanda and must defend his nation from hidden enemies.",
      type: "Movie",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2018,
      duration: "2h 14m",
      rating: "7.3",
    },
    {
      id: 10,
      title: "The Mandalorian",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9032/1751047759032-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/9084/1751047729084-v",
      description: "A lone bounty hunter travels the galaxy, protecting a mysterious child.",
      type: "Series",
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2019,
      duration: "3 Seasons",
      rating: "8.7",
    },
    {
      id: 11,
      title: "Avatar",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3232/1423232-i-050f622bde39",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3229/1423229-v-38316a3e497f",
      description: "A marine on an alien world struggles between duty and a newfound connection with nature.",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure", "Fantasy"],
      year: 2009,
      duration: "2h 42m",
      rating: "7.9",
    },
    {
      id: 12,
      title: "Joker",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5857/1745986875857-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/8429/1745986818429-v",
      description: "A failed comedian spirals into madness and becomes Gotham’s notorious villain.",
      type: "Movie",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2019,
      duration: "2h 2m",
      rating: "8.4",
    },
    {
      id: 13,
      title: "Money Heist",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7149/1751706547149-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6876/1751706436876-v",
      description: "A mastermind gathers criminals to carry out the biggest heist in Spain’s history.",
      type: "Series",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2017,
      duration: "5 Seasons",
      rating: "8.2",
    },
    {
      id: 14,
      title: "Spider-Man: No Way Home",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7626/1755603447626-i",
      thumbnail: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/4109/1755603424109-t",
      description: "Peter Parker seeks help from Doctor Strange, unleashing chaos across the multiverse.",
      type: "Movie",
      genre: ["Action", "Adventure", "Fantasy"],
      year: 2021,
      duration: "2h 28m",
      rating: "8.3",
    },
  ];

  top10Card=[
    {
      id: 1,
      title: "Inception",
      thumbnailLarge: "https://img10.hotstar.com/image/upload/f_auto,q_auto/sources/r1/cms/prod/173/1755108910173-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/805/1755108030805-v",
      description: "A thief enters people’s dreams to steal secrets, but faces the ultimate heist of planting an idea.",
      type: "Movie",
      genre: ["Sci-Fi", "Thriller", "Action"],
      year: 2010,
      duration: "2h 28m",
      rating: "8.8",
    },
    {
      id: 2,
      title: "The Dark Knight",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5928/1752777915928-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5928/1752777915928-i",
      description: "Batman faces his greatest test against the Joker, who seeks to plunge Gotham into chaos.",
      type: "Movie",
      genre: ["Action", "Crime", "Drama"],
      year: 2008,
      duration: "2h 32m",
      rating: "9.0",
    },
    {
      id: 3,
      title: "Interstellar",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4015/1753382974015-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1007/1753382821007-v",
      description: "A team of explorers travels through a wormhole in space to save humanity from extinction.",
      type: "Movie",
      genre: ["Sci-Fi", "Adventure", "Drama"],
      year: 2014,
      duration: "2h 49m",
      rating: "8.6",
    },
    {
      id: 4,
      title: "Stranger Things",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/2369/1754054652369-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6353/1754054576353-v",
      description: "Kids uncover dark secrets when a friend disappears and a strange girl with powers appears.",
      type: "Series",
      genre: ["Mystery", "Thriller", "Sci-Fi"],
      year: 2016,
      duration: "4 Seasons",
      rating: "8.7",
    },
    {
      id: 5,
      title: "Breaking Bad",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7085/1715414277085-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/227/1715414310227-v",
      description: "A chemistry teacher turned meth kingpin struggles to secure his family’s future.",
      type: "Series",
      genre: ["Crime", "Drama", "Thriller"],
      year: 2008,
      duration: "5 Seasons",
      rating: "9.5",
    },
    {
      id: 6,
      title: "The Matrix",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/5195/1739947245195-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/7578/1739947237578-v",
      description: "A hacker discovers that reality is a simulation and joins a rebellion against machines.",
      type: "Movie",
      genre: ["Sci-Fi", "Action"],
      year: 1999,
      duration: "2h 16m",
      rating: "8.7",
    },
    {
      id: 7,
      title: "Game of Thrones",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/1675/1715415371675-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/4517/1715415404517-v",
      description: "Noble families vie for the Iron Throne as an ancient threat rises in the north.",
      type: "Series",
      genre: ["Fantasy", "Drama", "Adventure"],
      year: 2011,
      duration: "8 Seasons",
      rating: "9.2",
    },
    {
      id: 8,
      title: "The Lion King",
      thumbnailLarge: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/6145/1747850756145-i",
      thumbnail: "https://img.hotstar.com/image/upload/f_auto,q_90,w_384/sources/r1/cms/prod/3262/1749545603262-v",
      description: "A lion cub flees after tragedy strikes, only to return and reclaim his kingdom.",
      type: "Movie",
      genre: ["Animation", "Drama", "Adventure"],
      year: 1994,
      duration: "1h 28m",
      rating: "8.5",
    },
  ]

}
